#!/bin/zsh -l

#causes no end of grief
xscreensaver -no-splash &

xinput set-prop "DELL07E6:00 06CB:76AF Touchpad" "libinput Tapping Enabled" 1

xrdb -merge .Xdefaults

xmodmap $HOME/.Xmodmap

exec ssh-agent xmonad | dzen2 -ta r -fg '#999999' -bg '#262626' -e 'button2=menuprint;button3=menuprint;button1=menuprint' -dock
